name: mnist
channels:
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - matplotlib=3.7
  - jupyter
  - intel-openmp=2021
  - mkl=2021
  - mkl-service=2
  - cpuonly
  - pytorch=2.2.2
  - torchvision=0.17.2
